modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/CakeChomps/issues"
logoFile="cake_chomps_icon.png"
[[mods]]
modId="cakechomps"
version="${version}"
displayName="Cake Chomps"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cake-chomps"
authors="C4"
description='''
Adds sound and crumb particles when you eat cake.
'''
[[dependencies.cakechomps]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.cakechomps]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
