# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=12.0.0+1.21.4-alpha
group=com.illusivesoulworks.cakechomps
java_version=21

# Common
minecraft_version=1.21.4
mod_name=Cake Chomps
mod_author=Illusive Soulworks
mod_id=cakechomps
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/cakechomps/issues
sources_url=https://github.com/illusivesoulworks/cakechomps
description=Adds sound and crumb particles when you eat cake.
minecraft_version_range=[1.21.4, 1.22)
minecraft_version_range_alt=~1.21.4

# Parchment
parchment_mc=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_version=0.119.4+1.21.4
fabric_loader_version=0.16.14

# Forge
forge_version=54.1.0
forge_version_range=[54,)

# NeoForge
neoforge_version=21.4.155
neoforge_version_range=[21.4,)

# Publishing
cf_id=307943
cf_page=https://www.curseforge.com/minecraft/mc-mods/cake-chomps
modrinth_id=g646EoqQ
modrinth_page=https://modrinth.com/mod/cake-chomps
release_type=release
release_versions=1.21.4
changelog_link=https://github.com/illusivesoulworks/cakechomps/blob/1.21.x/CHANGELOG.md
discord_thumbnail=https://media.forgecdn.net/avatars/180/83/636790863104893595.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
